package com.exceptionprograme;

public class ExceptionDemo {

	public static void main(String[] args) {
		
		String a = args[1];

		try {

			Integer s = new Integer("abb");

		

			int i = 10 / 0;

			System.out.println(i);

			System.out.println(s);

		} catch (ArithmeticException | NumberFormatException  e) {

			System.out.println("Array out of bound Exception is handled");

			System.out.println("Number format exception is handend");

			System.out.println("Divdie by zero exception is handeld");

			e.printStackTrace();
		}

	}

}
